
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01Ea3dPVEV6TVRjd05sb1hEVE13TURrd056RXpNVGN3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTURQClNRN3pRRlo4UndETldaR1hBdGhxSVlacklMMzFQYXloOTRJaFJmUDJoZmx4WTZpaDVuY0hQSTZrdTBaaEkvaE4KL0ZraXRESXFnSEc1ZDcxcU12UzVoTUM4V3NUcGVKbmFINXpES0tDWHlsalV4UHlBS05MMGxFUE1paWtsejBpMQplWEJyZkFLdmk3eVZuSUQxZzBYd2ljZTQ0dElsQVpsV3UraWVrUkdoZ0QvOUc0dkU1SWx3aDN6RHNCanJiQUw2Ck1kZkV5bEVTZ1hOa1cyVW5kVEt0VXFxdnhSVmtyNDBjU1ltSkFsSEV0dktLMTdHVkJWUzVBSjliZHRxc2NQcEIKTStyUU4ySGIvV21raUU4Vk5GM2hOa0R6dXVWU0ovRW1hbitzcXdYUWEyZ20wdG1NU1NrUjk1eDRvUTd2NlBRbwp0MWMwaXprVnlIZXV6UzdVUEk4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLRlhiVUZGaFhrVjY4bStCdGxpbFc1ZTRDc1dNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCSUdNQnJPWFdoRmJIUmtkWUFTZDY1YU9nT2VhVVZKSzREaWpGemE0dklFV2NmaTRjLwpoR3N0S29Fc29KVmgxWXlXeG9UKy9ORzRvRkp6MG00YXlLSWZCOEdKdEk4Y3BSdlp4REJUZlN2YzNxbzdGYXRlCnZIbStGNldFTHNYcTl4UGVvMCtCdnBTRHFuaU9RUDJKdkZLMm5NdjdKR3h4a3l6U1F3S3RZa0oxMXdLOWx6WlgKRmdqQmRGMlc3b29ybGV2MnNtamd3VUpFREVHTlg1WXViSUZtYkdtUDZBYmhRRkNPQWNDZnZOYUNVSWtOY2RDZwoyaWJ3SVhhRjNsLzRUeXlGTVFKNE5SdkFHOWYwb2pjeHpvU3NCcVZNOGRRVDBBMkdjbnNSejZkaTFFamROUjhWCksvTW02aXpOcUc0ZWQrbUhpVi9VdFJDT3BBTTJKUkY1SVNuVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://192.168.121.15:9443 https://192.168.121.15:9443/1
  failurePolicy: Fail
  name: mcniinterface.kb.io
  rules:
  - apiGroups:
    - batch.sdewan.akraino.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cniinterfaces

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01Ea3dPVEV6TVRjd05sb1hEVE13TURrd056RXpNVGN3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTURQClNRN3pRRlo4UndETldaR1hBdGhxSVlacklMMzFQYXloOTRJaFJmUDJoZmx4WTZpaDVuY0hQSTZrdTBaaEkvaE4KL0ZraXRESXFnSEc1ZDcxcU12UzVoTUM4V3NUcGVKbmFINXpES0tDWHlsalV4UHlBS05MMGxFUE1paWtsejBpMQplWEJyZkFLdmk3eVZuSUQxZzBYd2ljZTQ0dElsQVpsV3UraWVrUkdoZ0QvOUc0dkU1SWx3aDN6RHNCanJiQUw2Ck1kZkV5bEVTZ1hOa1cyVW5kVEt0VXFxdnhSVmtyNDBjU1ltSkFsSEV0dktLMTdHVkJWUzVBSjliZHRxc2NQcEIKTStyUU4ySGIvV21raUU4Vk5GM2hOa0R6dXVWU0ovRW1hbitzcXdYUWEyZ20wdG1NU1NrUjk1eDRvUTd2NlBRbwp0MWMwaXprVnlIZXV6UzdVUEk4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLRlhiVUZGaFhrVjY4bStCdGxpbFc1ZTRDc1dNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCSUdNQnJPWFdoRmJIUmtkWUFTZDY1YU9nT2VhVVZKSzREaWpGemE0dklFV2NmaTRjLwpoR3N0S29Fc29KVmgxWXlXeG9UKy9ORzRvRkp6MG00YXlLSWZCOEdKdEk4Y3BSdlp4REJUZlN2YzNxbzdGYXRlCnZIbStGNldFTHNYcTl4UGVvMCtCdnBTRHFuaU9RUDJKdkZLMm5NdjdKR3h4a3l6U1F3S3RZa0oxMXdLOWx6WlgKRmdqQmRGMlc3b29ybGV2MnNtamd3VUpFREVHTlg1WXViSUZtYkdtUDZBYmhRRkNPQWNDZnZOYUNVSWtOY2RDZwoyaWJ3SVhhRjNsLzRUeXlGTVFKNE5SdkFHOWYwb2pjeHpvU3NCcVZNOGRRVDBBMkdjbnNSejZkaTFFamROUjhWCksvTW02aXpOcUc0ZWQrbUhpVi9VdFJDT3BBTTJKUkY1SVNuVQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: https://192.168.121.15:9443/1
  failurePolicy: Fail
  name: vcniinterface.kb.io
  rules:
  - apiGroups:
    - batch.sdewan.akraino.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cniinterfaces
