# permissions for end users to view cniinterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cniinterface-viewer-role
rules:
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cniinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.sdewan.akraino.org
  resources:
  - cniinterfaces/status
  verbs:
  - get
